# Generated by Django 4.2.7 on 2024-12-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('secid', models.CharField(max_length=17, unique=True, verbose_name='Код документа')),
                ('regnumber', models.CharField(blank=True, max_length=63, null=True, verbose_name='Номер государственной регистрации')),
                ('name', models.CharField(max_length=255, verbose_name='Полное наименование')),
                ('emitent_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Информация о ценных бумагах',
                'verbose_name_plural': 'Информация о ценных бумагах',
                'ordering': ['secid'],
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tradedate', models.DateField(verbose_name='Дата проведения торгов')),
                ('numtrades', models.FloatField(verbose_name='Количество сделок за торговый день')),
                ('open', models.FloatField(blank=True, null=True, verbose_name='Цена первой сделки')),
                ('close', models.FloatField(blank=True, null=True, verbose_name='Цена послеторгового периода')),
                ('secid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='mo_ex.security', to_field='secid')),
            ],
            options={
                'verbose_name': 'История торгов за произвольную дату',
                'verbose_name_plural': 'История торгов за произвольную дату',
            },
        ),
    ]
